apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-openstack-credentials
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: external-secrets-openstack-credentials
                # anything not staging or prod use this version
                addonChartVersion: main
                addonChartRepository: https://github.com/valiton-k8s-blueprints/charts.git
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: main
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: main
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - repoURL: '{{.values.addonChartRepository}}'
          path: 'bws/{{.values.addonChart}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              clusterSecrets:
                serviceAccountName: '{{.metadata.annotations.cluster_secret_service_account}}'
                namespace: '{{.metadata.annotations.cluster_secret_namespace}}'
                name: '{{.metadata.annotations.cluster_secret_name}}'            
              cinderCsiPlugin:
                authUrl: {{.metadata.annotations.openstack_auth_url}}
              externalDns:
                authUrl: {{.metadata.annotations.openstack_auth_url}}
              certManagerDesignateWebhook:
                authUrl: {{.metadata.annotations.openstack_auth_url}}
              openstackCloudControllerManager:
                authUrl: {{.metadata.annotations.openstack_auth_url}}
                loadBalancer:
                  subnetId: {{.metadata.annotations.openstack_subnet_id}}
                  floatingNetworkId: {{.metadata.annotations.openstack_floating_network_id}}
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
