apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: kubelet-serving-cert-approver
    spec:
      project: default
      source:
        path: deploy/standalone
        repoURL: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
        targetRevision: v0.9.0
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
