---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-designate-webhook
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChartVersion: helm-0.6.2
                addonChartRepository: https://github.com/syseleven/designate-certmanager-webhook.git
              selector:
                matchExpressions:
                  - key: enable_cert_manager_designate_webhook
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: helm-0.6.2
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: helm-0.6.2
  template:
    metadata:
      name: 'cert-manager-designate-webhook'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - path: helm/designate-certmanager-webhook
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: 'cert-manager-designate-webhook'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/cert-manager-designate-webhook/values.yaml
              - $values/config/cert-manager-designate-webhook/{{.metadata.labels.environment}}.yaml
            values: |
              credentialsSecret: {{.metadata.annotations.cert_manager_designate_webhook_secret_name}}
              certManager:
                namespace: {{.metadata.annotations.cert_manager_namespace}}
                serviceAccountName: {{.metadata.annotations.cert_manager_service_account_name}}
      destination:
        namespace: '{{.metadata.annotations.cert_manager_designate_webhook_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
