---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openstack-cloud-controller-manager
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: openstack-cloud-controller-manager
                addonChartRepository: https://kubernetes.github.io/cloud-provider-openstack
          - clusters:
              selector:
                matchLabels:
                  environment: staging
          - clusters:
              selector:
                matchLabels:
                  environment: production
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '2.32.0'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/{{.values.addonChart}}/values.yaml
              - $values/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              secret:
                enabled: true
                create: false
              cluster:
                name: {{.name}}
      destination:
        namespace: kube-system
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
