---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cinder-csi-plugin
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: cinder-csi-plugin
                addonChartRepository: https://github.com/kubernetes/cloud-provider-openstack
              selector:
                matchExpressions:
                  - key: enable_cinder_csi_plugin
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
          - clusters:
              selector:
                matchLabels:
                  environment: production
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - path: charts/cinder-csi-plugin
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: 'v1.32.0'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/{{.values.addonChart}}/values.yaml
              - $values/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              storageClass:
                delete:
                  isDefault: true
              clusterID: '{{.metadata.annotations.cluster_name}}'
              secret:
                enabled: true
                name: '{{.metadata.annotations.cinder_csi_plugin_secret_name}}'
              csi:
                plugin:
                  volumes:
                    - name: cacert
                      hostPath:
                        path: /etc/ssl/certs/ca-certificates
      destination:
        namespace: '{{.metadata.annotations.cinder_csi_plugin_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
