---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: external-dns
                # anything not staging or prod use this version
                addonChartVersion: 1.14.3
                addonChartRepository: https://kubernetes-sigs.github.io/external-dns
              selector:
                matchExpressions:
                  - key: enable_external_dns
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 1.14.3
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: 1.14.3
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              provider: aws
              {{- if .metadata.annotations.base_nodepool_labels}}
              nodeSelector:
                {{.metadata.annotations.base_nodepool_labels}}
              {{- end }}
              serviceAccount:
                name: {{.metadata.annotations.external_dns_service_account}}
                annotations:
                  eks.amazonaws.com/role-arn: '{{.metadata.annotations.external_dns_iam_role_arn}}'
              domainFilters: {{.metadata.annotations.external_dns_domain_filters}}
              txtOwnerId: {{.metadata.annotations.aws_cluster_name}}
              policy: {{default "upsert-only" .metadata.annotations.external_dns_policy}}
      destination:
        namespace: '{{.metadata.annotations.external_dns_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
