controller:
  ingressClassResource:
    name: nginx
    default: true
  config:
    use-proxy-protocol: "true"
  service:
    externalTrafficPolicy: "Local"
    annotations:
      loadbalancer.openstack.org/proxy-protocol: "true"
      loadbalancer.openstack.org/enable-health-monitor: "true"
